title: " Kingdom of Muscadet"
baseline: The only Muscadet issued from the Hellfest soil in Clisson
description: The only Muscadet issued from the Hellfest soil in Clisson
baseurl: /
canonicalurl: true
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
date:
  format: j F Y
  timezone: Europe/Paris
hyde:
  sidebar:
    sticky: true
  theme: "red"
  reverse: true
